### ISSUE TITLE
feature/nidium (Nidium platform support)

### ISSUE THREAD

**Issue by cookiengineer** [Artificial-Engineering/lycheejs#186]
Nidium seems to be an amazing environment to fertilize apps. Currently, they seem to have Linux and OSX support (android branch is unstable) only, but it's worth to support this environment as it heavily reduces app package size compared to nw.js (or electron for that matter).

**BLOCKED through upstream** implementations:

- [ ] `lychee.Stash` requires `fs.createDirSync()`
- [ ] `lychee.net.socket.HTTP` requires `socket.onread()` and `socket.port` per-remote (upstream issue `#76`)
- [ ] `lychee.net.socket.WS` requires `socket.onread()` and `socket.port` per-remote (upstream issue `#76`)
- [ ] `lychee.ui.entity.Upload` requires `list[]` array with values (upstream issue `#87`)
- [ ] `lychee.Input` requires correct keycodes (upstream issue `#89`)

Upstream Pull Requests and Issues 😞 

- [x] https://github.com/nidium/libapenetwork/pull/55
- [x] https://github.com/nidium/Nidium/pull/75
- [ ] https://github.com/nidium/Nidium/pull/77
- [ ] (issue) https://github.com/nidium/Nidium/issues/76
- [ ] (issue) https://github.com/nidium/Nidium/issues/87
- [ ] (issue) https://github.com/nidium/Nidium/issues/89

The following implementations need to be done:

- [x] `lychee.Renderer`
- [x] `lychee.Input`
- [x] `lychee.Storage`
- [x] `lychee.Viewport`
- [x] `Buffer` is similar to the `html` platform port, but should use `Uint8Array` and `ArrayBuffer` behind the scenes in the socket-specific adapters for nidium
- [x] `Config`
- [x] `Font` is identical to `html` platform, using the same parsing algorithm
- [ ] `Music`, `Sound` uses the Audio.getContext() API which is similar to Web Audio. Both mp3 and ogg are supported.
- [x] `Texture` `.buffer` property should be a `new Image()` instance (similar to `html` platform)
- [x] `Stuff` can use `global.require(path)` ([API](https://www.nidium.com/docs/api/master/Nidium/global#global.require__static))
- [x] `lychee.net.Server`
- [x] `lychee.net.Client`
- [ ] `lychee.ui.entity.Download` (Save File dialog?)
- [ ] `lychee.ui.entity.Upload` needs to use `window.openFileDialog(['jpg'], function(files) {});` ([API reference](https://github.com/nidium/Nidium/blob/master/src/Binding/JSWindow.cpp#L1119-L1120))
- [x] `lychee.ui.entity.Helper` needs to spawn `window.exec("lycheejs-helper <args>")` but the helper needs to properly use an exit code, otherwise nidium will wait and hang.

The following fixes need to be applied:

- [x] Add `nidium` platform to `studio.ui.element.modify.Project`
- [x] Add `nidium` to `./bin/helper.sh`
- [x] Add `nidium` to `./bin/runtime`
- [x] Add `nidium` to `fertilizer.template` for both Application and Library

Relevant upstream issues and discussions:

- Networking: https://github.com/nidium/Nidium/issues/61
- Packaging: https://github.com/nidium/Nidium/issues/24
- (Helper) spawning Processes: https://github.com/nidium/Nidium/issues/62
- (Helper / server): https://github.com/nidium/Nidium/issues/69
- File Open/Save Dialog: https://github.com/nidium/Nidium/issues/63
- (Viewport) Window resizing / Fullscreen support: https://github.com/nidium/Nidium/issues/65

**Comment by cookiengineer** [comment]
Notes for runtime support:

- The installer needs the `--noexec --keep` flags, then the binary is extracted into `nidium.tmp/dist/nidium`.

**Comment by cookiengineer** [comment]
The Nidium Server build currently has no support for the `lychee.ui.entity.Helper`. This is blocking for the server-variant. Upstream reference issue: https://github.com/nidium/Nidium/issues/69

**Comment by cookiengineer** [comment]
As of https://github.com/Artificial-Engineering/lycheejs-runtime/commit/f8be6767a7d4ae823ba537f254e63125f9b993b4 the lycheejs runtime repository has support for nidium, auto-update-able and auto-package-able.

**Comment by cookiengineer** [comment]
The `lychee.Stash` implementation requires something like `mkdir()` as an API. As this is currently not available, the related upstream issue is https://github.com/nidium/Nidium/issues/74

**Comment by cookiengineer** [comment]
**BLOCKING**: No socket.port property available with the server socket's onaccept callback, therefore no p2p capabilities.

Upstream pull request: https://github.com/nidium/Nidium/pull/75

**Comment by cookiengineer** [comment]
*BLOCKING*:

The socket.onread callback is fired incorrectly, there's no socket.onread callback fired per-client. It currently is only per-server on the server-side, which prevents us from using the `lychee.net.socket` concept.

Upstream issue is https://github.com/nidium/Nidium/issues/76

**Comment by cookiengineer** [comment]
This issue is now set **ON HOLD** due to upstream problems merging pull-requests and well, architectural problems from server-side and frontend-side in their build system. Moved to 2017-Q3.

**Comment by cookiengineer** [comment]
The `nidium` platform is now merged into the `development` branch. As far as it is possible for the current state of nidium (`v0.2`), these are the missing features:

- `lychee.ui.entity.Download` to save/store files, which _should_ be technologically possible with the `window.openDirDialog(callback)` API.
- `lychee.ui.entity.Upload` to open/read files, which _should_ be technologically possible with the `window.openFileDialog(types, callback)` API.

**Unclear Implementation state**:

The `global.Socket` API in nidium is in a kind of broken state, as it does not allow per-socket or per-tunnel connections on the server side and will fire receive/send events every time a single packet reaches a single endpoint. This has to be debugged further, and synchronized with the upstream issues.

- `lychee.net.socket.HTTP`
- `lychee.net.socket.WS`
- `lychee.net.Server`

**Impossible Features and Implementations**:

- `lychee.Viewport` has no `fullscreen` support. Even without a fullscreen API, without a `window.right/bottom` property it is impossible to implement as a polyfill.
- `lychee.Input` has no `mousewheel` support, because both `addEventListener('mousewheel')` and `_onmousewheel` do not fire anything, ever, in any constellation.
- `lychee.Input` has no `touch` support, because there's only a (single) mouse-API implemented and available.

**Comment by cookiengineer** [comment]
The `lychee.Input` is now tested and it is verified that upstream `nidium` currently has several issues with keycode ranges. This issue is on hold until upstream issues are resolved.

**Comment by 2075** [comment]
any update on this?

**Comment by cookiengineer** [comment]
It's still the same state as before.

The underlying problem is that the `nidium` project and their other core devs are kind of totally inactive. So yeah, it's still in a broken state, still has the unicode problems and most likely will not be fixed soon.

They are currently heavily working on the Windows support, so the keyboard translation stuff for non-French keyboards is for them rather unimportant (wat?) and if the features are to be developed, most likely we would have to implement it for ourselves in a downstream fork.

Merging with upstream is no problem, though. Usually their response time is within 48h or so.

This is essentially the reason why I currently prioritized the `node-sdl` runtime higher than `nidium` because the unfamiliar C-codebase is really hard to get your head around with... and most likely will end up with similar bugs without a proper test suite that requires a shitload of time.
